version: "3.8"
services:
  postgres11:
    image: "postgres:11"
    container_name: "postgres11"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
  mongo:
    image: mongo
    container_name: "mongo"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
  sqlserver2019:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: "sqlserver2019"
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Secret@123
      MSSQL_PID: Developer
  elasticsearch:
    image: elasticsearch:7.10.1
    container_name: "elasticsearch"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      "discovery.type": "single-node"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  kibana:
    image: kibana:7.10.1
    container_name: "kibana"
    ports:
      - "5601:5601"
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
  redis:
    image: redis:6
    container_name: "redis"
    ports:
      - "6379:6379"
volumes:
  pgdata:
    external: true
  elasticsearch:
    external: true
networks:
  default:
    external:
      name: local-network